## **PC3**

In [5]:
dataRepo='https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/appendData'
levels=range(1,5)
fileNames=['/level'+str(level)+'.xlsx' for level in levels]
alltheLinks=[dataRepo+fn for fn in fileNames]
alltheLinks

['https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/appendData/level1.xlsx',
 'https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/appendData/level2.xlsx',
 'https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/appendData/level3.xlsx',
 'https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/appendData/level4.xlsx']

***LIMPIEZA***

In [39]:
#Primer link
import pandas as pd
link=alltheLinks[0]
data = pd.read_excel(link)
data.drop(index=[0, 1, 2], inplace=True)
nuevos_titulos=list(data.iloc[0])
data.columns = nuevos_titulos
data.drop(index=3,inplace=True)
data_nan=data.dropna(axis=1, how='all')
data_cleaned = data_nan.loc[:, data_nan.columns.notna()].copy()
data_cleaned.reset_index(drop=True, inplace=True)
data_cleaned.drop(index=[0, 1], inplace=True)
data_cleaned1 = data_cleaned.dropna(subset=['HDI rank'])
data_cleaned2 = data_cleaned1.replace(',', '.', regex=True)
data_cleaned2.iloc[:, 2:] = data_cleaned2.iloc[:, 2:].astype(float)
data_cleaned2.reset_index(drop=True, inplace=True)
data_cleaned2 = data_cleaned2.loc[:, ~data_cleaned2.columns.duplicated()]
data_cleaned2

<ipython-input-39-085281eb37ba>:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data_cleaned2 = data_cleaned1.replace(',', '.', regex=True)
<ipython-input-39-085281eb37ba>:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2      5.0
3      6.0
4     11.0
5      6.0
6     18.0
      ...
63    -8.0
64    17.0
65    -1.0
66     4.0
67     6.0
Name: GNI per capita rank minus HDI rank, Length: 66, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_cleaned2.iloc[:, 2:] = data_cleaned2.iloc[:, 2:].astype(float)
<ipython-input-39-085281eb37ba>:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '2      3.0
3      1.0
4      2.0
5      4.0
6      5.0
      ...
63    61.0
64    64.0
65    62.0
66    62.0
67    64.0
Name: HDI rank, Length: 66, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data_cleaned2.iloc[:, 2:] = data_cleaned2.iloc[:, 2:].astype(float)

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5.0
1,2,Norway,0.961,83.2339,18.185200,13.00363,64660.10622,6.0
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11.0
3,4,Hong Kong. China (SAR),0.952,85.4734,17.278170,12.22621,62606.84540,6.0
4,5,Australia,0.951,84.5265,21.054590,12.72682,49238.43335,18.0
...,...,...,...,...,...,...,...,...
61,62,Malaysia,0.803,74.8839,13.343040,10.64506,26657.94355,-8.0
62,63,Georgia,0.802,71.6940,15.568520,12.82222,14664.16825,17.0
63,63,Mauritius,0.802,73.5552,15.173530,10.42791,22025.34631,-1.0
64,63,Serbia,0.802,74.1923,14.400090,11.36987,19123.02747,4.0
65,66,Thailand,0.800,78.7154,15.882219,8.69712,17030.15352,6.0

In [40]:
#Segundo link
link=alltheLinks[1]
data = pd.read_excel(link)
data.drop(index=[0, 1], inplace=True)
data.drop(index=3,inplace=True)
data_nan=data.dropna(axis=1, how='all')
data_cleaned = data_nan.dropna(axis=1)
data_cleaned.reset_index(drop=True, inplace=True)
data2_cleaned2 = data_cleaned.replace(',', '.', regex=True)
data2_cleaned2.iloc[:, 2:] = data2_cleaned2.iloc[:, 2:].astype(float)
data2_cleaned2

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
0,67.0,Albania,0.796,76.4626,14.448000,11.286455,14131.110390,17.0,68.0
1,68.0,Grenada,0.795,74.9362,18.662020,9.032104,13483.577400,18.0,70.0
2,70.0,Barbados,0.790,77.5714,15.713385,9.852701,12306.341000,26.0,71.0
3,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.365950,2.0,71.0
4,72.0,Seychelles,0.785,71.2945,13.941610,10.283120,25830.617750,-17.0,69.0
5,73.0,Sri Lanka,0.782,76.3991,14.139905,10.827300,12578.220550,21.0,75.0
6,74.0,Bosnia and Herzegovina,0.780,75.3003,13.800000,10.536320,15241.914650,4.0,73.0
7,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.332120,-16.0,76.0
8,76.0,Iran (Islamic Republic of),0.774,73.8749,14.615250,10.636453,13000.711700,15.0,77.0
9,77.0,Ukraine,0.773,71.6240,14.956569,11.131420,13255.509770,11.0,78.0
10,78.0,North Macedonia,0.770,73.8415,13.624432,10.228150,15917.752830,-3.0,79.0
11,79.0,China,0.768,78.2107,14.236115,7.600118,17504.399690,-8.0,82.0
12,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.600370,-11.0,82.0
13,80.0,Moldova (Republic of),0.767,68.8459,14.433000,11.821590,14875.331890,-1.0,81.0
14,80.0,Palau,0.767,66.0204,15.784320,12.491430,13818.678690,5.0,80.0
15,83.0,Cuba,0.764,73.6829,14.443060,12.497734,7878.847482,37.0,73.0
16,84.0,Peru,0.762,72.3769,15.387734,9.885519,12245.893660,13.0,85.0
17,85.0,Armenia,0.759,72.0431,13.116760,11.330300,13157.993900,4.0,87.0
18,86.0,Mexico,0.758,70.2127,14.864440,9.221050,17896.294980,-16.0,88.0
19,87.0,Brazil,0.754,72.7504,15.599060,8.128814,14369.888480,-5.0,86.0
20,88.0,Colombia,0.752,72.8296,14.442750,8.862860,14384.356660,-7.0,88.0
21,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.833430,11961.087920,11.0,82.0
22,90.0,Maldives,0.747,79.9182,12.635610,7.322000,15448.127880,-14.0,97.0
23,91.0,Algeria,0.745,76.3767,14.626896,8.069284,10800.225460,13.0,96.0
24,91.0,Azerbaijan,0.745,69.3658,13.496890,10.542970,14256.744560,-8.0,100.0
25,91.0,Tonga,0.745,70.9857,16.048571,11.392594,6822.031250,34.0,90.0
26,91.0,Turkmenistan,0.745,69.2644,13.210400,11.261390,13020.715500,-1.0,93.0
27,95.0,Ecuador,0.740,73.6700,14.624230,8.817120,10311.632730,11.0,99.0
28,96.0,Mongolia,0.739,70.9754,14.980350,9.423700,10588.225320,9.0,90.0
29,97.0,Egypt,0.731,70.2207,13.786500,9.573026,11731.690560,4.0,97.0
30,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,10257.544770,10.0,94.0
31,99.0,Fiji,0.730,67.1140,14.736790,10.921548,9980.110866,9.0,94.0
32,99.0,Suriname,0.730,70.2743,13.035644,9.776801,12672.200330,-6.0,92.0
33,101.0,Uzbekistan,0.727,70.8616,12.477140,11.895590,7916.785725,18.0,107.0
34,102.0,Dominica,0.720,72.8140,13.319186,8.142186,11487.624220,0.0,106.0
35,102.0,Jordan,0.720,74.2563,10.646560,10.446680,9923.714974,8.0,104.0
36,104.0,Libya,0.718,71.9112,12.854280,7.599985,15335.712000,-27.0,117.0
37,105.0,Paraguay,0.717,70.2617,12.987991,8.861840,12349.286000,-10.0,100.0
38,106.0,Palestine. State of,0.715,73.4727,13.358010,9.938480,6582.899416,21.0,109.0
39,106.0,Saint Lucia,0.715,71.1114,12.866110,8.545040,12048.303810,-7.0,104.0
40,108.0,Guyana,0.714,65.6734,12.502722,8.617477,22464.657340,-47.0,107.0
41,109.0,South Africa,0.713,62.3410,13.643710,11.373160,12948.373250,-17.0,102.0
42,110.0,Jamaica,0.709,70.5003,13.404920,9.154629,8834.475670,4.0,110.0
43,111.0,Samoa,0.707,72.7675,12.418859,11.403800,5307.953374,24.0,112.0
44,112.0,Gabon,0.706,65.8210,12.977310,9.436000,13366.934550,-25.0,113.0
45,112.0,Lebanon,0.706,75.0472,11.285870,8.718636,9525.831467,-1.0,103.0
46,114.0,Indonesia,0.705,67.5703,13.748894,8.556510,11466.068360,-11.0,116.0
47,115.0,Viet Nam,0.703,73.6181,12.951932,8.370280,7867.371345,6.0,113.0

In [41]:
#Tercer link
link=alltheLinks[2]
data = pd.read_excel(link)
data.drop(index=[0, 1], inplace=True)
data.drop(index=3,inplace=True)
data_nan=data.dropna(axis=1, how='all')
data_cleaned = data_nan.dropna(axis=1)
data_cleaned.reset_index(drop=True, inplace=True)
data3_cleaned2 = data_cleaned.replace(',', '.', regex=True)
data2_cleaned2.iloc[:, 2:] = data2_cleaned2.iloc[:, 2:].astype(float)
data3_cleaned2

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
0,116.0,Philippines,0.699,69.2664,13.126570,8.969100,8920.428468,-3.0,113.0
1,118.0,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.827750,8111.190194,0.0,119.0
2,118.0,Kyrgyzstan,0.692,69.9774,13.195300,11.374106,4566.303831,26.0,121.0
3,120.0,Venezuela (Bolivarian Republic of),0.691,70.5536,12.816080,11.107277,4810.882621,20.0,118.0
4,121.0,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
5,122.0,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
6,123.0,Belize,0.683,70.4697,12.991690,8.847600,6309.099778,6.0,120.0
7,123.0,Morocco,0.683,74.0419,14.151910,5.916000,7302.819170,1.0,122.0
8,125.0,El Salvador,0.675,70.7479,12.671348,7.150930,8295.665889,-8.0,124.0
9,126.0,Nicaragua,0.667,73.8368,12.641358,7.144000,5624.793595,6.0,129.0
10,127.0,Bhutan,0.666,71.8150,13.225005,5.170262,9437.541512,-15.0,125.0
11,128.0,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
12,129.0,Bangladesh,0.661,72.3811,12.441980,7.379060,5472.104781,4.0,128.0
13,130.0,Tuvalu,0.641,64.5466,9.404430,10.573108,6351.435899,-2.0,131.0
14,131.0,Marshall Islands,0.639,65.2688,10.239320,10.883140,4619.535393,12.0,131.0
15,132.0,India,0.633,67.2398,11.874620,6.655109,6589.980037,-6.0,130.0
16,133.0,Ghana,0.632,63.7954,12.047780,8.329887,5744.504017,-2.0,135.0
17,134.0,Micronesia (Federated States of),0.628,70.7100,11.549480,7.804956,3696.173945,22.0,136.0
18,135.0,Guatemala,0.627,69.2368,10.562450,5.681300,8723.285317,-20.0,133.0
19,136.0,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
20,137.0,Honduras,0.621,70.1229,10.132814,7.088480,5297.955301,-1.0,138.0
21,138.0,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
22,139.0,Namibia,0.615,59.2690,11.927207,7.192013,8633.504452,-23.0,134.0
23,140.0,Lao People's Democratic Republic,0.607,68.0608,10.136110,5.374000,7699.579617,-18.0,142.0
24,140.0,Timor-Leste,0.607,67.7369,12.616098,5.436790,4460.869435,7.0,140.0
25,140.0,Vanuatu,0.607,70.4490,11.535315,7.064846,3085.411633,23.0,142.0
26,143.0,Nepal,0.602,68.4495,12.886950,5.121793,3877.315444,10.0,144.0
27,144.0,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596000,7678.591873,-21.0,141.0
28,145.0,Equatorial Guinea,0.596,60.5943,9.734940,5.910863,12073.959930,-47.0,147.0
29,146.0,Cambodia,0.593,69.5835,11.467720,5.088000,4078.697154,3.0,148.0
30,146.0,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
31,148.0,Angola,0.586,61.6434,12.172100,5.417391,5465.617791,-14.0,149.0
32,149.0,Myanmar,0.585,65.6716,10.909138,6.376800,3850.524234,5.0,145.0
33,150.0,Syrian Arab Republic,0.577,72.0627,9.164220,5.100000,4191.933893,-2.0,152.0
34,151.0,Cameroon,0.576,60.3334,13.108599,6.151310,3620.932408,6.0,150.0
35,152.0,Kenya,0.575,61.4270,10.698558,6.652000,4473.570344,-6.0,150.0
36,153.0,Congo,0.571,63.5187,12.330815,6.166000,2889.283521,11.0,153.0
37,154.0,Zambia,0.565,61.2234,10.928760,7.187091,3217.767739,7.0,154.0
38,155.0,Solomon Islands,0.564,70.3477,10.328690,5.711848,2481.511362,13.0,155.0
39,156.0,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
40,156.0,Papua New Guinea,0.558,65.3506,10.360771,4.740000,4008.623573,-4.0,157.0
41,158.0,Mauritania,0.556,64.3636,9.376160,4.918805,5075.305711,-20.0,158.0
42,159.0,Côte d'Ivoire,0.550,58.5983,10.675580,5.199139,5217.448516,-22.0,159.0

In [42]:
#cuarto link
link=alltheLinks[-1]
data = pd.read_excel(link)
data_nan=data.dropna(axis=1, how='all')
data_cleaned = data_nan.dropna(axis=1)
data_cleaned.reset_index(drop=True, inplace=True)
data4_cleaned2 = data_cleaned.replace(',', '.', regex=True)
data4_cleaned2 = data4_cleaned2.drop(columns=[data4_cleaned2.columns[2]])
data4_cleaned2.iloc[:, 2:] = data4_cleaned2.iloc[:, 2:].astype(float)
data4_cleaned2

<ipython-input-42-8b828dd5d8c5>:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0      7.0
1    -19.0
2     12.0
3      2.0
4    -22.0
5      6.0
6     -7.0
7      6.0
8     -2.0
9     13.0
10   -10.0
11   -32.0
12   -14.0
13     8.0
14    -1.0
15    -5.0
16     3.0
17     0.0
18     7.0
19     9.0
20    -2.0
21    -1.0
22   -13.0
23     1.0
24    -8.0
25     2.0
26   -11.0
27     4.0
28     1.0
29    -3.0
30    -7.0
31    -1.0
Name: GNI per capita rank minus HDI rank, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data4_cleaned2.iloc[:, 2:] = data4_cleaned2.iloc[:, 2:].astype(float)

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,160,Tanzania (United Republic of),0.549,66.2007,9.221490,6.372899,2664.329096,7.0
1,161,Pakistan,0.544,66.0979,8.658350,4.536330,4623.705430,-19.0
2,162,Togo,0.539,61.6194,12.950494,5.016807,2166.619062,12.0
3,163,Haiti,0.535,63.1924,9.700000,5.554000,2847.500746,2.0
4,163,Nigeria,0.535,52.6760,10.127584,7.181074,4790.284425,-22.0
5,165,Rwanda,0.534,66.0722,11.230970,4.425292,2209.795202,6.0
6,166,Benin,0.525,59.8210,10.766680,4.304786,3408.965923,-7.0
7,166,Uganda,0.525,62.7048,10.149870,5.730942,2181.436510,6.0
8,168,Lesotho,0.514,53.0620,12.040878,6.010185,2700.435748,-2.0
9,169,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064,13.0
10,170,Senegal,0.511,67.0926,8.963750,2.937938,3344.311825,-10.0
11,171,Djibouti,0.509,62.3049,7.432980,4.100000,5024.993944,-32.0
12,172,Sudan,0.508,65.2667,7.945188,3.820000,3575.190840,-14.0
13,173,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983,8.0
14,174,Gambia,0.500,62.0830,9.418626,4.637487,2172.207664,-1.0
15,175,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604,-5.0
16,176,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667,3.0
17,177,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.241590,0.0
18,178,Liberia,0.481,60.7472,10.420790,5.082000,1288.742350,7.0
19,179,Congo (Democratic Republic of the),0.479,59.1930,9.817864,7.018697,1076.098781,9.0
20,180,Afghanistan,0.478,61.9824,10.263844,2.985070,1824.190915,-2.0
21,181,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579,-1.0
22,182,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182,-13.0
23,183,Yemen,0.455,63.7534,9.098710,3.200000,1314.270189,1.0
24,184,Burkina Faso,0.449,59.2696,9.142100,2.114962,2117.915916,-8.0
25,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924,2.0
26,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443,-11.0
27,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4.0
28,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1.0
29,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3.0
30,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0
31,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1.0

***PARTE I***

In [43]:
import pandas as pd
allDFs=[data_cleaned2, data2_cleaned2, data3_cleaned2, data4_cleaned2]
allColumnNames=[]
for df in allDFs:
    allColumnNames.append(set(df.columns))
[len(cols) for cols in allColumnNames]

[8, 9, 9, 8]

In [48]:
commonColumns=set.intersection(*allColumnNames)
len(commonColumns),commonColumns

(8,
 {'Country',
  'Expected years of schooling',
  'GNI per capita rank minus HDI rank',
  'Gross national income (GNI) per capita',
  'HDI rank',
  'Human Development Index (HDI) ',
  'Life expectancy at birth',
  'Mean years of schooling'})

In [49]:
set.union(*allColumnNames)-commonColumns

{'HDI rank.1'}

In [54]:
allDFs_sameNames=[df.loc[:,list(commonColumns)] for df in allDFs]
allDFsConcat=pd.concat(allDFs_sameNames)
allDFsConcat.reset_index(drop=True, inplace=True)
allDFsConcat.columns = allDFsConcat.columns.str.replace(' ', '', regex=True)
allDFsConcat

,HDIrank,GNIpercapitarankminusHDIrank,Lifeexpectancyatbirth,Expectedyearsofschooling,HumanDevelopmentIndex(HDI),Meanyearsofschooling,Grossnationalincome(GNI)percapita,Country
0,1.0,5.0,83.9872,16.500299,0.962,13.859660,66933.004540,Switzerland
1,2.0,6.0,83.2339,18.185200,0.961,13.003630,64660.106220,Norway
2,3.0,11.0,82.6782,19.163059,0.959,13.767170,55782.049810,Iceland
3,4.0,6.0,85.4734,17.278170,0.952,12.226210,62606.845400,Hong Kong. China (SAR)
4,5.0,18.0,84.5265,21.054590,0.951,12.726820,49238.433350,Australia
...,...,...,...,...,...,...,...,...
184,187.0,4.0,61.6627,10.722722,0.426,3.129267,731.786709,Burundi
185,188.0,1.0,53.8947,8.040172,0.404,4.334000,966.058611,Central African Republic
186,189.0,-3.0,61.5763,6.957112,0.400,2.116717,1239.866936,Niger
187,190.0,-7.0,52.5254,8.035914,0.394,2.573774,1364.169417,Chad
188,191.0,-1.0,54.9752,5.542510,0.385,5.726140,767.787000,South Sudan

***PARTE 2***

In [74]:
linkf='https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/countryCODES.xlsx'
df1=pd.read_excel(linkf)
df2=allDFsConcat
union=df1.merge(df2,left_on='Country',right_on='Country',  how='outer')

union

,Country,Officialstatename,InternetccTLD,iso2,iso3,HDIrank,GNIpercapitarankminusHDIrank,Lifeexpectancyatbirth,Expectedyearsofschooling,HumanDevelopmentIndex(HDI),Meanyearsofschooling,Grossnationalincome(GNI)percapita
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALBANIA,The Republic of Albania,.al,AL,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANGOLA,The Republic of Angola,.ao,AO,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
355,Yemen,NaN,NaN,NaN,NaN,183.0,1.0,63.7534,9.098710,0.455,3.200000,1314.270189
356,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,Zambia,NaN,NaN,NaN,NaN,154.0,7.0,61.2234,10.928760,0.565,7.187091,3217.767739
359,Zimbabwe,NaN,NaN,NaN,NaN,146.0,9.0,59.2531,12.110969,0.593,8.710909,3809.887158

In [ ]:

Segundo: Cuando haya integrado los archivos anteriores, haga un merge entre ese archivo, y el archivo countryCODES.xlsx.

Tercero: Con los archivos fallecidosCOVID.csv,  haga un reporte mensual de fallecidos. Solo debe mostrar por fila el mes (y año) y cuanto fallecidos hubo en ese mes.

Cuarto: Use el mismo archivo anterior. Esta vez haga un reporte de fallecidos por mes, pero el tipo de muerte debe estar en columnas separadas.

***PARTE 3***

In [ ]:
import pandas as pd
link='https://github.com/Controles-ICDE-Ochoa/PC3_2024.2/raw/d516b1cb4f3fc8664a280227547618747279ffd1/fallecidosCOVID.csv'